// source: weather.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('weather_testorg_test_weather_1.WeatherRequest', null, global);
goog.exportSymbol('weather_testorg_test_weather_1.WeatherResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
weather_testorg_test_weather_1.WeatherRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(weather_testorg_test_weather_1.WeatherRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  weather_testorg_test_weather_1.WeatherRequest.displayName = 'weather_testorg_test_weather_1.WeatherRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
weather_testorg_test_weather_1.WeatherResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(weather_testorg_test_weather_1.WeatherResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  weather_testorg_test_weather_1.WeatherResponse.displayName = 'weather_testorg_test_weather_1.WeatherResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
weather_testorg_test_weather_1.WeatherRequest.prototype.toObject = function(opt_includeInstance) {
  return weather_testorg_test_weather_1.WeatherRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!weather_testorg_test_weather_1.WeatherRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
weather_testorg_test_weather_1.WeatherRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
city: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!weather_testorg_test_weather_1.WeatherRequest}
 */
weather_testorg_test_weather_1.WeatherRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new weather_testorg_test_weather_1.WeatherRequest;
  return weather_testorg_test_weather_1.WeatherRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!weather_testorg_test_weather_1.WeatherRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!weather_testorg_test_weather_1.WeatherRequest}
 */
weather_testorg_test_weather_1.WeatherRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCity(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
weather_testorg_test_weather_1.WeatherRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  weather_testorg_test_weather_1.WeatherRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!weather_testorg_test_weather_1.WeatherRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
weather_testorg_test_weather_1.WeatherRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCity();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string city = 1;
 * @return {string}
 */
weather_testorg_test_weather_1.WeatherRequest.prototype.getCity = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!weather_testorg_test_weather_1.WeatherRequest} returns this
 */
weather_testorg_test_weather_1.WeatherRequest.prototype.setCity = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
weather_testorg_test_weather_1.WeatherResponse.prototype.toObject = function(opt_includeInstance) {
  return weather_testorg_test_weather_1.WeatherResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!weather_testorg_test_weather_1.WeatherResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
weather_testorg_test_weather_1.WeatherResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
city: jspb.Message.getFieldWithDefault(msg, 1, ""),
country: jspb.Message.getFieldWithDefault(msg, 2, ""),
temperature: jspb.Message.getFieldWithDefault(msg, 3, ""),
condition: jspb.Message.getFieldWithDefault(msg, 4, ""),
humidity: jspb.Message.getFieldWithDefault(msg, 5, ""),
windSpeed: jspb.Message.getFieldWithDefault(msg, 6, ""),
lastUpdated: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!weather_testorg_test_weather_1.WeatherResponse}
 */
weather_testorg_test_weather_1.WeatherResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new weather_testorg_test_weather_1.WeatherResponse;
  return weather_testorg_test_weather_1.WeatherResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!weather_testorg_test_weather_1.WeatherResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!weather_testorg_test_weather_1.WeatherResponse}
 */
weather_testorg_test_weather_1.WeatherResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCity(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCountry(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTemperature(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setCondition(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setHumidity(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setWindSpeed(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setLastUpdated(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
weather_testorg_test_weather_1.WeatherResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  weather_testorg_test_weather_1.WeatherResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!weather_testorg_test_weather_1.WeatherResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
weather_testorg_test_weather_1.WeatherResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCity();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCountry();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTemperature();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getCondition();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getHumidity();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getWindSpeed();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getLastUpdated();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * optional string city = 1;
 * @return {string}
 */
weather_testorg_test_weather_1.WeatherResponse.prototype.getCity = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!weather_testorg_test_weather_1.WeatherResponse} returns this
 */
weather_testorg_test_weather_1.WeatherResponse.prototype.setCity = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string country = 2;
 * @return {string}
 */
weather_testorg_test_weather_1.WeatherResponse.prototype.getCountry = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!weather_testorg_test_weather_1.WeatherResponse} returns this
 */
weather_testorg_test_weather_1.WeatherResponse.prototype.setCountry = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string temperature = 3;
 * @return {string}
 */
weather_testorg_test_weather_1.WeatherResponse.prototype.getTemperature = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!weather_testorg_test_weather_1.WeatherResponse} returns this
 */
weather_testorg_test_weather_1.WeatherResponse.prototype.setTemperature = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string condition = 4;
 * @return {string}
 */
weather_testorg_test_weather_1.WeatherResponse.prototype.getCondition = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!weather_testorg_test_weather_1.WeatherResponse} returns this
 */
weather_testorg_test_weather_1.WeatherResponse.prototype.setCondition = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string humidity = 5;
 * @return {string}
 */
weather_testorg_test_weather_1.WeatherResponse.prototype.getHumidity = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!weather_testorg_test_weather_1.WeatherResponse} returns this
 */
weather_testorg_test_weather_1.WeatherResponse.prototype.setHumidity = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string wind_speed = 6;
 * @return {string}
 */
weather_testorg_test_weather_1.WeatherResponse.prototype.getWindSpeed = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!weather_testorg_test_weather_1.WeatherResponse} returns this
 */
weather_testorg_test_weather_1.WeatherResponse.prototype.setWindSpeed = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string last_updated = 7;
 * @return {string}
 */
weather_testorg_test_weather_1.WeatherResponse.prototype.getLastUpdated = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!weather_testorg_test_weather_1.WeatherResponse} returns this
 */
weather_testorg_test_weather_1.WeatherResponse.prototype.setLastUpdated = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


goog.object.extend(exports, weather_testorg_test_weather_1);
